# image: "scorpil/rust:nightly"
image: rust:latest

services:
    - postgres:latest

test:cargo:
    script:
        - cargo test
    cache:
        paths:
            - target/
            - caargo/


variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
