# image: "scorpil/rust:nightly"
image: rust:latest

services:
    - postgres:latest

test:cargo:
    script:
        - apt-get install -y exiftool
        - cargo test --color=always
    cache:
        paths:
            - target/
            - cargo/


variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    RUST_BACKTRACE: 1
