language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust
      - stable
      - beta

#Ignore submodules since the backend does not care about frontend
git:
    submodules: false
