[package]
name = "flash"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@gmail.com>"]

[dependencies]
iron = "*"
staticfile = "*"
mount = "*"
persistent = "*"
urlencoded = "*"

rand = "*"
glob = "*"
rustc-serialize = "*"
regex = "*"
lazy_static = "*"

image = "*"
immeta = "*"
#immeta = { git = "https://github.com/tdryer/immeta", branch = "jpeg-exif" }

diesel = { version = "0.11.0", features = ["postgres", "chrono"] }
diesel_codegen = { version = "0.11.0", features = ["postgres"] }
dotenv = "0.8.0"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]
